# Generated by Django 3.0.7 on 2020-06-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_season_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='number',
            new_name='season_number',
        ),
    ]
