# Generated by Django 3.0.7 on 2020-06-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0003_remove_episodequeen_lip_sync_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='lip_sync_artist',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='lip_sync_song',
        ),
    ]
