# Generated by Django 3.0.7 on 2020-06-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queens', '0003_queen_lip_syncs'),
        ('episodes', '0005_auto_20200610_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='queens',
            field=models.ManyToManyField(through='episodes.EpisodeQueen', to='queens.Queen'),
        ),
    ]
