# Generated by Django 3.0.7 on 2020-06-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('home_city', models.TextField(default='')),
                ('home_state', models.TextField(default='')),
                ('home_country', models.TextField(default='')),
            ],
            options={
                'db_table': 'queens',
            },
        ),
    ]
