# Generated by Django 3.0.7 on 2020-06-08 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='queen',
            table='queen',
        ),
    ]
