# Generated by Django 3.0.7 on 2020-06-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lip_syncs', '0003_lipsyncqueen_result'),
        ('queens', '0002_auto_20200608_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='queen',
            name='lip_syncs',
            field=models.ManyToManyField(to='lip_syncs.LipSync'),
        ),
    ]
