# Generated by Django 3.0.7 on 2020-06-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0006_episode_queens'),
        ('queens', '0003_queen_lip_syncs'),
    ]

    operations = [
        migrations.AddField(
            model_name='queen',
            name='episodes',
            field=models.ManyToManyField(through='episodes.EpisodeQueen', to='episodes.Episode'),
        ),
        migrations.AlterField(
            model_name='queen',
            name='name',
            field=models.TextField(default='', unique=True),
        ),
    ]
